#Prometheus yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'springboot-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.0.22:8086']  # Cuando se despliegue se cambia 'localHost' cuando se realice el desplieguea
