name: Call Webhook on Push

on:
  push:
    branches:
      - master

jobs:
  call_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Call Webhook Server
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: "http://45.55.149.182:5000/webhook"
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "repository": "${{ github.repository }}", "ref": "${{ github.ref }}" }'
          webhook_type: json
          verbose: true
          content_type: application/json
        env:
          webhook_url: "http://45.55.149.182:5000/webhook"
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_headers: '{"X-Webhook-Secret": "${{ secrets.WEBHOOK_SECRET }}"}'

